export class TransferDetails {
    dtfilechr;
    etatfilechr;
    suppRefChrfile;
    refChrfile;
    chrNomprenom;
    chrNationalite;
    departPlace;
    dtDepart;
    dropoffCity;
    numVol;
    pickupType;
    pickupName;
    pickupTime;
    dropoffType;
    dropoffName;
    dtReturn;
    nbrPerson;
    typeRent;
    vehiculeDesc;
    chrComment;
    etatFactFrs;
    idDevachat;
    mntAchatChr;
    idDevagcy;
    mntServChr;
    uniqueId;
    officeidGds;
    idfilechr;
    codeDevise;
  email: any;
  gds: any;
  luggage;
  driver;
}
