export class BookingDetails {
    numPnr;
    passengers = [];
    segments = [];
    extraServices;
    etat;
    tktTimeLimit;
    dateEtat;
    editedBy;
    success;
    canBeVoid;
    erreur;
    fareBasic;
    tax;
    totalFare;
    currencyCode;
    uniqueId;
    mntExtra;
    classVol;
    codeGds;
    idTiers;
    tiersName;
    ticketedOn;
    importedOn;
    sector;
    customerCharge;
    decimalPlaces;
    history = [];
    canBeRefund;
    canBeReIssue;
    airlinePnr;
    user;
    officeId;
}
